### ISSUE TITLE
Unable to start `serve` or `cms` tasks

### ISSUE THREAD

**Issue by dsasko** [importantimport/lume_theme_shiraha#3]
On a freshly installed Lume with Shirhara theme I get an error when trying to start `serve` or `cms` tasks.

OS: MacOS v15.0.1
Deno: v2.0.0
Lume: v2.3.3

## Steps to reproduce

1. `> deno run -A https://lume.land/init.ts`
2. `> (install a theme)`
3. `> (_config.ts)`
4. `> (Shiraha)`
5. `> deno task cms` or `> deno task serve`
6. Observe error in terminal

## Error message for `deno task cms`
```
error: Uncaught (in worker "") (in promise) TypeError: Module not found "https://deno.land/x/lume@v2.3.3/cms.ts".
    at https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.5/_cms.ts:1:21
  const mod = await import(toFileUrl(cmsConfig).href);
              ^
    at async build (https://deno.land/x/lume@v2.3.3/cli/cms_worker.ts:35:15)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
```

## Error message for `deno task serve`
```
error: Uncaught (in worker "") (in promise) TypeError: Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import meta from "../deno.json" assert { type: "json" };

  at https://deno.land/x/skia_canvas@0.5.5/src/ffi.ts:13:1

    const mod = await import(url);
                ^
    at async createSite (https://deno.land/x/lume@v2.3.3/cli/utils.ts:26:17)
    at async buildSite (https://deno.land/x/lume@v2.3.3/cli/utils.ts:45:16)
    at async build (https://deno.land/x/lume@v2.3.3/cli/build_worker.ts:35:16)
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
```

**Comment by kwaa** [comment]
The cms entry was removed in the new version of Lume. I will update later.

**Comment by kwaa** [comment]
This issue should have been fixed.
I can't test it in detail now, so feel free to reopen it if you still have problems.

**Comment by dsasko** [comment]
Sorry but it seems both problems are still present.

I deleted the lume installation folder and tried installing it from scratch again. I'm not quite sure if there is some caching going on but just to make sure everything is aligned here is the imports section from the json config:

```
  "imports": {
    "lume/": "https://deno.land/x/lume@v2.3.3/",
    "shiraha/": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.5/",
    "shiraha/jsx-runtime": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.5/jsx-runtime.ts",
    "lume/cms/": "https://cdn.jsdelivr.net/gh/lumeland/cms@v0.7.0/"
  },
```

**Comment by kwaa** [comment]
> Sorry but it seems both problems are still present.

Oops... I forgot to release a new version.

**Comment by kwaa** [comment]
v0.1.0-alpha.6 has been released.

```diff
  "imports": {
    "lume/": "https://deno.land/x/lume@v2.3.3/",
-   "shiraha/": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.5/",
+   "shiraha/": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.6/",
-   "shiraha/jsx-runtime": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.5/jsx-runtime.ts",
+   "shiraha/jsx-runtime": "https://deno.land/x/lume_theme_shiraha@v0.1.0-alpha.6/jsx-runtime.ts",
    "lume/cms/": "https://cdn.jsdelivr.net/gh/lumeland/cms@v0.7.0/"
  },
```
